
exports.up = function(knex) {
     return knex.schema.createTable( "users",( table) => {
          table.uuid("id")
               .primary()
               .notNullable();
          table.string("username")
               .unique()
               .notNullable();
          table.string("email")
               .unique()
               .notNullable();
          table.string("password")
               .unique()
               .notNullable();
          table.string("contact")
               .unique()
               .notNullable();
          table.string("role")
               .defaultTo("user");
          table.boolean("initiated")
               .defaultTo(false);
          table.timestamps(true,true);
     })
     .createTable("upline",(table)=>{
          table.uuid("id")
               .primary()
               .notNullable();
          table.string("uplineID")
               .notNullable();
          table.string("username")
               .notNullable();
          table.uuid("user")
               .notNullable();
          table.foreign("user")
               .references("id")
               .inTable("users");
     })
     .createTable("wallet",(table)=>{
          table.uuid("id")
               .primary()
               .notNullable();
          table.float("total")
               .default(0.0);
          table.uuid("user")
               .notNullable();
          table.foreign("user")
               .references("id")
               .inTable("users");
     })
     .createTable("streams",(table)=>{
          table.uuid("id")
               .primary()
               .notNullable();
          table.string("type")
               .notNullable();
          table.float("total")
               .default(0.0);
          table.uuid("walletID")
               .notNullable();
          table.foreign("walletID")
               .references("id")
               .inTable("wallet");
     })
     .createTable("tier", (table) => {
          table.uuid("id")
               .primary()
               .notNullable();
          table.string("type")
               .notNullable();
          table.float("amount")
               .defaultTo(0.0);
          table.float("interest")
               .defaultTo(0.0);
          table.string("touch")
               .notNullable();
          table.uuid("user")
               .notNullable();
          table.foreign("user")
               .references("id")
               .inTable("users");
          table.timestamps(true,true)
     })
     .createTable("tokens", (table)=>{
          table.string("RefreshToken")
               .primary()
               .notNullable();
          table.string("AccessToken")
               .notNullable();
          table.timestamps(true,true)
     })
     .createTable("orders",(table)=>{
          table.uuid("id")
               .primary()
               .notNullable();
          table.uuid("userID")
               .notNullable();
          table.string("ordered")
               .notNullable();
          table.float("amount")
               .defaultTo(0.0);
          table.timestamps(true,true)
     })
     .createTable("mpesa", (table) => {
          table.uuid("id")
               .primary()
               .notNullable();
          table.string("_id")
               .unique()
               .notNullable();
          table.string("tx_ref")
               .unique()
               .notNullable();
          table.uuid("userID")
               .notNullable();
          table.string("status")
               .defaultTo("pending");
          table.float("amount")
               .defaultTo(0.0);
          table.string("contact")
               .notNullable();
          table.boolean("verified")
               .defaultTo(false);
          table.string("ipAddress")
               .notNullable();
          table.string("userAgent")
                   .notNullable();
          table.string("email")
                   .notNullable();
          table.string("fbp");
          table.timestamps(true,true);
     })
     .createTable("boxes",(table)=>{
          table.uuid("id")
               .primary()
               .notNullable();
          table.decimal("loc");
          table.float("value")
               .defaultTo(0.0);
          table.uuid("user")
               .notNullable();
          table.foreign("user")
               .references("id")
               .inTable("users");
     })
     .createTable("records",(table)=>{
          table.uuid("id")
               .primary()
               .notNullable();
          table.uuid("userID")
               .notNullable();
          table.string("type")
               .notNullable();
          table.string("status")
               .notNullable();
     })
   };
   
   exports.down = function(knex) {
       return knex.schema.dropTable("users")
                         .dropTable("upline")
                         .dropTable("wallet")
                         .dropTable("streams")
                         .dropTable("tokens")
                         .dropTable("orders")
                         .dropTable("mpesa")
                         .dropTable("tier")
                         .dropTable("records")
                         .dropTable("boxes");
   };
   