<template>
    <v-card class="pa-4" flat>
        <p>READ THE FOLLOWING RULES CAREFULLY BEFORE REGISTERING AN ACCOUNT.</p>
        <p>YOU AGREE TO BE OF LEGAL AGE IN YOUR COUNTRY TO PARTAKE IN THIS PROGRAM AND IN ALL THE CASES YOUR MINIMAL AGE MUST BE 18 YEARS.</p>
        <p>Cloud360 IS NOT AVAILABLE TO THE GENERAL PUBLIC AND ITS OPENED ONLY TO THE QUALIFIED MEMBERS OF Cloud360, THE USE OF THIS SITE IS RESTRICTED TO OUR MEMBERS AND INDIVIDUALS PERSONALLY INVITED BY THEM. EVERY DEPOSIT IS CONSIDERED TO BE A PRIVATE TRANSACTION BETWEEN THE Cloud360 AND ITS MEMBERS.</p>
        <p>AS A PRIVATE TRANSACTION, THIS PROGRAM IS EXEMPT FROM THE SECURITIES ACT OF 1993, THE SECURITIES ACT OF 1934 AND THE INVESTMENT ACT OF 1940 AND ALL OTHER RULES, REGULATIONS AND AMENDMENTS THEREOF. WE ARE NOT FDIC INSURED. WE ARE NOT A LICENSED BANK OR A SECURITY FIRM.</p>
        <p>YOU AGREE THAT ALL INFORMATION, COMMUNICATIONS, MATERIALS COMING FROM Cloud360 ARE UNSOLICITED AND MUST BE KEPT PRIVATE, CONFIDENTIAL AND PROTECTED FROM ANY DISCLOSURE. MOREOVER, THE INFORMATION, COMMUNICATIONS AND MATERIALS CONTAINED HEREIN ARE NOT TO BE REGARDED AS AN OFFER, NOR A SOLICITATION FOR INVESTMENTS IN ANY JURISDICTION WHICH DEEMS NON-PUBLIC OFFERS OR SOLICITATIONS UNLAWFUL, NOR TO ANY PERSON TO WHOM IT WILL BE UNLAWFUL TO MAKE SUCH OFFER OR SOLICITATION.</p>
        <p>ALL THE DATA GIVEN BY A MEMBER TO Cloud360 WILL BE ONLY PRIVATELY USED AND NOT DISCLOSED TO ANY THIRD PARTIES. Cloud360 IS NOT RESPONSIBLE OR LIABLE FOR ANY LOSS OF DATA.</p>
        <p>YOU AGREE TO HOLD ALL PAYMENTS AND MEMBERS HARMLESS OF ANY LIABLITY. YOU ARE INVESTING AT YOUR OWN RISK AND YOU AGREE THAT A PAST PERFOMANCE IS NOT AN EXPLICIT GUARANTEE FOR THE SAME FUTURE PERFOMANCE. YOU AGREE THAT ALL INFORMATION, COMMUNICATIONS AND MATERIALS YOU WILL FIND ON THIS SITE ARE INTENDED TO BE REGARDED AS AN INFORMATION AND EDUCATIONAL MATTER AND NOT AN INVESTMENT ADVICE.</p>
        <p>WE RESERVE THE RIGHT TO CHANGE THE RULES, COMMISSIONS AND RATES OF THE PROGRAM AT NAY TIME AND AT OUR SOLE DISCRETION WITHOUT NOTICE, ESPECIALLY IN ORDER TO RESPECT THE INTEGRITY AND SECURITY OF THE MEMBERS' INTEREST. YOU AGREE THAT IT IS YOUR SOLE RESPONSIBILTY TO REVIEW THE CURRETNT TERMS.</p>
        <p>Cloud360 IS NOT RESPONSIBLE OR LIABLE FOR ANY DAMAGES, LOSSES AND COSTS RESULTING FROM ANY VIOLATION OF THE CONDITIONS AND TERMS AND/OR USE OF OUR WEBSITE BY A MEMBER. YOU GUARANTEE TO Cloud360 THAT YOU WILL NOT USE THIS SITE IN ANY ILLEGAL WAY AND YOU AGREE TO RESPECT YOUR LOCAL, NATIONAL AND INTERNATIONAL LAWS.</p>
        <p>DON'T POST BAD VOTE ON PUBLIC FORUMS AND AT GOLD RATING SITE WITHOUT CONTACTING THE ADMINISTRATOR OF OUR PROGRAM FIRST. MAYBE THERE WAS A TECHNICAL PROBLEM WITH YOUR TRANSACTION, SO PLEASE ALWAYS CLEAR THE THING WITH THE ADMINISTRATOR.</p>
        <p>WE WILL NOT TOLERATE SPAM OR ANY TYPE OF UCE IN THIS PROGRAM. SPAM VIOLATORS WILL BE IMMEDIATELY AND PERMANENTLY REMOVED FROM THE PROGRAM.</p>
        <p>Cloud360 RESERVES THE RIGHT TO ACCEPT OR DECLINE ANY MEMBER FOR MEMBERSHIP WITHOUT EXPLANATION.</p>
    </v-card>
</template>

<script>
export default {
    head(){
        return {
            title:"Term and Conditions"
        }
    },
}
</script>